schema-version: v2
kind: plugin
metadata:
  name: stk-compose-multiplatform-template
  display-name: compose multiplatform
  description: Inicializar projeto sample compose multiplatform
  version: 0.0.1-test
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1-test.md
  requirements: docs/requirements.md
  single-use: False
  repository: https://github.com/lnsantos/stk-compose-multiplatform-template.git
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  stk-projects-only: false
  inputs:
    - label: insert name application example -> My App
      type: text
      name: app_name
      required: true
      pattern: '^[^:>#*]+|([^:>#*][^>#*]+[^:>#*])$'
      help: 'not permitted character special'

    - label: insert project name example -> MyApplication
      name: project_root_name
      type: text
      required: true
      pattern: '([A-Z][a-z]+)+'
      help: 'Inform your project name none character special' 

    - label: insert namespace project example -> com.lnsantos.br
      name: namespace
      type: text
      required: true
      pattern: '([a-z.]+)+'
      help: 'Inform your namespace (e.g.: com.lnsantos.br)'

computed-inputs:
   namespace_folder: "{{ namespace|replace('.','/') }}"
   bundle_id: "{{ namespace|project_root_name|join('.') }}"